AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

Metadata:
  AWS::ServerlessRepo::Application:
    Name: NvaCognitoPreTokenGenerationTrigger
    Description: NVA Cognito Pre Token Generation Trigger
    Author: Unit
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    Labels: ['${GIT_REPO}', '${CODEBUILD_RESOLVED_SOURCE_VERSION}', '@${BUILD_TIMESTAMP}']

Globals:
  Function:
    Timeout: 20

Parameters:
  CustomDomain:
    Type: String
    Description: Custom API to connect this lambda to
  UserServiceSecretName:
    Type: String
    Description: Name of the Secret for Users and Role Service
  UserServiceSecretKey:
    Type: String
    Description: Key in the Secret for Users and Role Service
  UserServiceSecretArn:
    Type: String
    Description: ARN to the Secret for Users and Role Service
  OutputName:
    Type: String
    Default: CognitoPreTokenGenerationTriggerArn
  MaxConcurrency:
    Type: String
    Description: Maximum capacity for provisioned concurrency
    Default: 10
  MinConcurrency:
    Type: String
    Description: Minimum capacity for provisioned concurrency
    Default: 1

Resources:
  
  TriggerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: writeLog
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*"
        - PolicyName: AddUserToGroup
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:AdminAddUserToGroup
                  - cognito-idp:AdminUpdateUserAttributes
                Resource: !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/*'
        - PolicyName: GetSecretValue
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref UserServiceSecretArn

  InvokePostAuthenticationTriggerPermission:
    DependsOn:
      - PreTokenGenerationTriggerAliaslive
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PreTokenGenerationTrigger
      Principal: cognito-idp.amazonaws.com

  InvokePostAuthenticationTriggerLivePermission:
    DependsOn:
      - PreTokenGenerationTriggerAliaslive
      - PreTokenGenerationTrigger
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub ${PreTokenGenerationTrigger}:live
      Principal: cognito-idp.amazonaws.com

  PreTokenGenerationTrigger:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cognito-pre-token-generation
      Handler: no.unit.nva.cognito.PostAuthenticationHandler::handleRequest
      Runtime: java11
      Role: !GetAtt TriggerExecutionRole.Arn
      MemorySize: 1408
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Timeout: 10
      Environment:
        Variables:
          CUSTOMER_API_SCHEME: https
          CUSTOMER_API_HOST: !Ref CustomDomain
          USER_API_SCHEME: https
          USER_API_HOST: !Ref CustomDomain
          USER_SERVICE_SECRET_NAME: !Ref UserServiceSecretName
          USER_SERVICE_SECRET_KEY: !Ref UserServiceSecretKey

  PreTokenGenerationTriggerScalableTarget:
    DependsOn:
      - PreTokenGenerationTriggerAliaslive
      - PreTokenGenerationTrigger
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: !Ref MaxConcurrency
      MinCapacity: !Ref MinConcurrency
      ResourceId: !Sub function:${PreTokenGenerationTrigger}:live
      RoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/lambda.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_LambdaConcurrency
      ScalableDimension: lambda:function:ProvisionedConcurrency
      ServiceNamespace: lambda

  PreTokenGenerationTriggerScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: utilization
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref PreTokenGenerationTriggerScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 0.70
        PredefinedMetricSpecification:
          PredefinedMetricType: LambdaProvisionedConcurrencyUtilization

  PreTokenGenerationTriggerArnParameter:
    DependsOn:
      - PreTokenGenerationTrigger
      - PreTokenGenerationTriggerAliaslive
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN to function handling PreTokenGeneration trigger for login.
      Name: !Ref OutputName
      Type: String
      Value: !Sub arn:aws:lambda:${AWS::AccountId}:function:${PreTokenGenerationTrigger}:live

Outputs:
  CognitoPreTokenGenerationFunction:
    Description: ARN Identifier of the PreTokenGenerationTrigger
    Value: !Sub arn:aws:lambda:${AWS::AccountId}:function:${PreTokenGenerationTrigger}:live
    Export:
      Name: !Ref OutputName
